I am going to proceed to pull data from the U.S. Census Bureau (American Community Survey via API)

I want to include county_name, median_income, population, state code, county code.

In [1]:
import pandas as pd
import requests
import matplotlib.pyplot as plt

In [2]:
#for only the year 2020

API_KEY = "45b4600dc3520340052a097a56a72fd6dee51fac"

url = (
    "https://api.census.gov/data/2020/acs/acs5"
    "?get=NAME,B19013_001E,B01003_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

response = requests.get(url)
data = response.json()

df_2020 = pd.DataFrame(data[1:], columns=data[0])

df_2020.rename(columns={
    "NAME": "county_name",
    "B19013_001E": "median_income",
    "B01003_001E": "population",
}, inplace=True)

df_2020.head()

               county_name median_income population state county
0  Autauga County, Alabama         57982      55639    01    001
1  Baldwin County, Alabama         61756     218289    01    003
2  Barbour County, Alabama         34990      25026    01    005
3     Bibb County, Alabama         51721      22374    01    007
4   Blount County, Alabama         48922      57755    01    009

Now I need to clean the columns so that the state is separate from county names. I also need to make the FIPS code for merging purposes. Then I will export it as a CSV.

In [3]:
df_2020["fips"] = df_2020["state"] + df_2020["county"]
df_2020.head()

               county_name median_income population state county   fips
0  Autauga County, Alabama         57982      55639    01    001  01001
1  Baldwin County, Alabama         61756     218289    01    003  01003
2  Barbour County, Alabama         34990      25026    01    005  01005
3     Bibb County, Alabama         51721      22374    01    007  01007
4   Blount County, Alabama         48922      57755    01    009  01009

In [4]:
df_2020.to_csv(
    "../data/census_acs_2020.csv",
    index=False
)

In [5]:
#year 2021

API_KEY = "45b4600dc3520340052a097a56a72fd6dee51fac"

url = (
    "https://api.census.gov/data/2021/acs/acs5"
    "?get=NAME,B19013_001E,B01003_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

response = requests.get(url)
data = response.json()

df_2021 = pd.DataFrame(data[1:], columns=data[0])

df_2021.rename(columns={
    "NAME": "county_name",
    "B19013_001E": "median_income",
    "B01003_001E": "population",
}, inplace=True)

df_2021.head()

               county_name median_income population state county
0  Autauga County, Alabama         62660      58239    01    001
1  Baldwin County, Alabama         64346     227131    01    003
2  Barbour County, Alabama         36422      25259    01    005
3     Bibb County, Alabama         54277      22412    01    007
4   Blount County, Alabama         52830      58884    01    009

In [6]:
df_2021["fips"] = df_2021["state"] + df_2021["county"]
df_2021.head()

               county_name median_income population state county   fips
0  Autauga County, Alabama         62660      58239    01    001  01001
1  Baldwin County, Alabama         64346     227131    01    003  01003
2  Barbour County, Alabama         36422      25259    01    005  01005
3     Bibb County, Alabama         54277      22412    01    007  01007
4   Blount County, Alabama         52830      58884    01    009  01009

In [7]:
df_2021.to_csv(
    "../data/census_acs_2021.csv",
    index=False
)

In [8]:
#year 2022

API_KEY = "45b4600dc3520340052a097a56a72fd6dee51fac"

url = (
    "https://api.census.gov/data/2022/acs/acs5"
    "?get=NAME,B19013_001E,B01003_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

response = requests.get(url)
data = response.json()

df_2022 = pd.DataFrame(data[1:], columns=data[0])

df_2022.rename(columns={
    "NAME": "county_name",
    "B19013_001E": "median_income",
    "B01003_001E": "population",
}, inplace=True)

df_2022.head()

               county_name median_income population state county
0  Autauga County, Alabama         68315      58761    01    001
1  Baldwin County, Alabama         71039     233420    01    003
2  Barbour County, Alabama         39712      24877    01    005
3     Bibb County, Alabama         50669      22251    01    007
4   Blount County, Alabama         57440      59077    01    009

In [9]:
df_2022["fips"] = df_2022["state"] + df_2022["county"]
df_2021.head()

               county_name median_income population state county   fips
0  Autauga County, Alabama         62660      58239    01    001  01001
1  Baldwin County, Alabama         64346     227131    01    003  01003
2  Barbour County, Alabama         36422      25259    01    005  01005
3     Bibb County, Alabama         54277      22412    01    007  01007
4   Blount County, Alabama         52830      58884    01    009  01009

In [10]:
df_2022.to_csv(
    "../data/census_acs_2022.csv",
    index=False
)

In [11]:
#year 2023

API_KEY = "45b4600dc3520340052a097a56a72fd6dee51fac"

url = (
    "https://api.census.gov/data/2021/acs/acs5"
    "?get=NAME,B19013_001E,B01003_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

response = requests.get(url)
data = response.json()

df_2023 = pd.DataFrame(data[1:], columns=data[0])

df_2023.rename(columns={
    "NAME": "county_name",
    "B19013_001E": "median_income",
    "B01003_001E": "population",
}, inplace=True)

df_2023.head()

               county_name median_income population state county
0  Autauga County, Alabama         62660      58239    01    001
1  Baldwin County, Alabama         64346     227131    01    003
2  Barbour County, Alabama         36422      25259    01    005
3     Bibb County, Alabama         54277      22412    01    007
4   Blount County, Alabama         52830      58884    01    009

In [12]:
df_2023["fips"] = df_2023["state"] + df_2023["county"]
df_2023.head()

               county_name median_income population state county   fips
0  Autauga County, Alabama         62660      58239    01    001  01001
1  Baldwin County, Alabama         64346     227131    01    003  01003
2  Barbour County, Alabama         36422      25259    01    005  01005
3     Bibb County, Alabama         54277      22412    01    007  01007
4   Blount County, Alabama         52830      58884    01    009  01009

In [13]:
df_2023.to_csv(
    "../data/census_acs_2023.csv",
    index=False
)

In [14]:
#year 2024

API_KEY = "45b4600dc3520340052a097a56a72fd6dee51fac"

url = (
    "https://api.census.gov/data/2024/acs/acs5"
    "?get=NAME,B19013_001E,B01003_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

response = requests.get(url)
data = response.json()

df_2024 = pd.DataFrame(data[1:], columns=data[0])

df_2024.rename(columns={
    "NAME": "county_name",
    "B19013_001E": "median_income",
    "B01003_001E": "population",
}, inplace=True)

df_2024.head()

               county_name median_income population state county
0  Autauga County, Alabama         72481      59947    01    001
1  Baldwin County, Alabama         78775     246989    01    003
2  Barbour County, Alabama         46042      24643    01    005
3     Bibb County, Alabama         52541      22130    01    007
4   Blount County, Alabama         64190      59518    01    009

In [15]:
df_2024["fips"] = df_2024["state"] + df_2024["county"]
df_2024.head()

               county_name median_income population state county   fips
0  Autauga County, Alabama         72481      59947    01    001  01001
1  Baldwin County, Alabama         78775     246989    01    003  01003
2  Barbour County, Alabama         46042      24643    01    005  01005
3     Bibb County, Alabama         52541      22130    01    007  01007
4   Blount County, Alabama         64190      59518    01    009  01009

In [16]:
df_2024.to_csv(
    "../data/census_acs_2024.csv",
    index=False
)