I am going to proceed to pull data from the U.S. Census Bureau (American Community Survey via API)

I want to include county_name, median_income, population, state code, county code.

In [2]:
import pandas as pd
import requests
import matplotlib.pyplot as plt

In [14]:
with open("./api_key.json", "r") as fi:
    api_key = json.load(fi)["api_key"]

In [23]:
#for only the year 2020
API_KEY = api_key

url_base = (
    "https://api.census.gov/data/2020/acs/acs5"
    "?get=NAME,B19013_001E,B01003_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

r1 = requests.get(url_base)

print(r1.status_code)
print(r1.text[:300])  

base = r1.json()

df_base = pd.DataFrame(base[1:], columns=base[0])

url_subject = (
    "https://api.census.gov/data/2020/acs/acs5/subject"
    "?get=NAME,S1701_C03_001E,S2301_C04_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

r2 = requests.get(url_subject)

print(r2.status_code)
print(r2.text[:300])

subject = r2.json()

df_subject = pd.DataFrame(subject[1:], columns=subject[0])


# Rename

df_base.rename(columns={
    "NAME": "county_name",
    "B19013_001E": "median_income",
    "B01003_001E": "population"
}, inplace=True)

df_subject.rename(columns={
    "S1701_C03_001E": "poverty_rate",
    "S2301_C04_001E": "unemployment_rate"
}, inplace=True)


# Merge

df_2020 = df_base.merge(
    df_subject[
        ["state","county","poverty_rate","unemployment_rate"]
    ],
    on=["state","county"],
    how="left"
)

# numeric conversion
cols = [
    "median_income",
    "population",
    "poverty_rate",
    "unemployment_rate"
]

df_2020[cols] = df_2020[cols].apply(
    pd.to_numeric,
    errors="coerce"
)

df_2020.head()

200
[["NAME","B19013_001E","B01003_001E","state","county"],
["Autauga County, Alabama","57982","55639","01","001"],
["Baldwin County, Alabama","61756","218289","01","003"],
["Barbour County, Alabama","34990","25026","01","005"],
["Bibb County, Alabama","51721","22374","01","007"],
["Blount County, Alaba
200
[["NAME","S1701_C03_001E","S2301_C04_001E","state","county"],
["Autauga County, Alabama","15.2","2.9","01","001"],
["Baldwin County, Alabama","9.2","3.9","01","003"],
["Barbour County, Alabama","28.6","6.9","01","005"],
["Bibb County, Alabama","18.1","7.4","01","007"],
["Blount County, Alabama","13.

,county_name,median_income,population,state,county,poverty_rate,unemployment_rate
0,"Autauga County, Alabama",57982,55639,01,001,15.2,2.9
1,"Baldwin County, Alabama",61756,218289,01,003,9.2,3.9
2,"Barbour County, Alabama",34990,25026,01,005,28.6,6.9
3,"Bibb County, Alabama",51721,22374,01,007,18.1,7.4
4,"Blount County, Alabama",48922,57755,01,009,13.7,5.2

Now I need to clean the columns so that the state is separate from county names. I also need to make the FIPS code for merging purposes. Then I will export it as a CSV.

In [24]:
df_2020["fips"] = df_2020["state"] + df_2020["county"]
df_2020.head()

,county_name,median_income,population,state,county,poverty_rate,unemployment_rate,fips
0,"Autauga County, Alabama",57982,55639,01,001,15.2,2.9,01001
1,"Baldwin County, Alabama",61756,218289,01,003,9.2,3.9,01003
2,"Barbour County, Alabama",34990,25026,01,005,28.6,6.9,01005
3,"Bibb County, Alabama",51721,22374,01,007,18.1,7.4,01007
4,"Blount County, Alabama",48922,57755,01,009,13.7,5.2,01009

In [25]:
df_2020.to_csv(
    "../data/raw/census_acs_2020.csv",
    index=False
)

In [26]:
#year 2021

API_KEY = api_key

url_base = (
    "https://api.census.gov/data/2021/acs/acs5"
    "?get=NAME,B19013_001E,B01003_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

r1 = requests.get(url_base)

print(r1.status_code)
print(r1.text[:300])  

base = r1.json()

df_base = pd.DataFrame(base[1:], columns=base[0])

url_subject = (
    "https://api.census.gov/data/2021/acs/acs5/subject"
    "?get=NAME,S1701_C03_001E,S2301_C04_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

r2 = requests.get(url_subject)

print(r2.status_code)
print(r2.text[:300])

subject = r2.json()

df_subject = pd.DataFrame(subject[1:], columns=subject[0])


# Rename

df_base.rename(columns={
    "NAME": "county_name",
    "B19013_001E": "median_income",
    "B01003_001E": "population"
}, inplace=True)

df_subject.rename(columns={
    "S1701_C03_001E": "poverty_rate",
    "S2301_C04_001E": "unemployment_rate"
}, inplace=True)


# Merge

df_2021 = df_base.merge(
    df_subject[
        ["state","county","poverty_rate","unemployment_rate"]
    ],
    on=["state","county"],
    how="left"
)

# numeric conversion
cols = [
    "median_income",
    "population",
    "poverty_rate",
    "unemployment_rate"
]

df_2021[cols] = df_2021[cols].apply(
    pd.to_numeric,
    errors="coerce"
)

df_2021.head()

200
[["NAME","B19013_001E","B01003_001E","state","county"],
["Autauga County, Alabama","62660","58239","01","001"],
["Baldwin County, Alabama","64346","227131","01","003"],
["Barbour County, Alabama","36422","25259","01","005"],
["Bibb County, Alabama","54277","22412","01","007"],
["Blount County, Alaba
200
[["NAME","S1701_C03_001E","S2301_C04_001E","state","county"],
["Autauga County, Alabama","13.6","2.8","01","001"],
["Baldwin County, Alabama","9.2","3.7","01","003"],
["Barbour County, Alabama","26.5","8.6","01","005"],
["Bibb County, Alabama","16.9","9.7","01","007"],
["Blount County, Alabama","13.

,county_name,median_income,population,state,county,poverty_rate,unemployment_rate
0,"Autauga County, Alabama",62660,58239,01,001,13.6,2.8
1,"Baldwin County, Alabama",64346,227131,01,003,9.2,3.7
2,"Barbour County, Alabama",36422,25259,01,005,26.5,8.6
3,"Bibb County, Alabama",54277,22412,01,007,16.9,9.7
4,"Blount County, Alabama",52830,58884,01,009,13.2,6.0

In [27]:
df_2021["fips"] = df_2021["state"] + df_2021["county"]
df_2021.head()

,county_name,median_income,population,state,county,poverty_rate,unemployment_rate,fips
0,"Autauga County, Alabama",62660,58239,01,001,13.6,2.8,01001
1,"Baldwin County, Alabama",64346,227131,01,003,9.2,3.7,01003
2,"Barbour County, Alabama",36422,25259,01,005,26.5,8.6,01005
3,"Bibb County, Alabama",54277,22412,01,007,16.9,9.7,01007
4,"Blount County, Alabama",52830,58884,01,009,13.2,6.0,01009

In [28]:
df_2021.to_csv(
    "../data/raw/census_acs_2021.csv",
    index=False
)

In [29]:
#year 2022

API_KEY = api_key

url_base = (
    "https://api.census.gov/data/2022/acs/acs5"
    "?get=NAME,B19013_001E,B01003_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

r1 = requests.get(url_base)

print(r1.status_code)
print(r1.text[:300])  

base = r1.json()

df_base = pd.DataFrame(base[1:], columns=base[0])

url_subject = (
    "https://api.census.gov/data/2022/acs/acs5/subject"
    "?get=NAME,S1701_C03_001E,S2301_C04_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

r2 = requests.get(url_subject)

print(r2.status_code)
print(r2.text[:300])

subject = r2.json()

df_subject = pd.DataFrame(subject[1:], columns=subject[0])


# Rename

df_base.rename(columns={
    "NAME": "county_name",
    "B19013_001E": "median_income",
    "B01003_001E": "population"
}, inplace=True)

df_subject.rename(columns={
    "S1701_C03_001E": "poverty_rate",
    "S2301_C04_001E": "unemployment_rate"
}, inplace=True)


# Merge

df_2022 = df_base.merge(
    df_subject[
        ["state","county","poverty_rate","unemployment_rate"]
    ],
    on=["state","county"],
    how="left"
)

# numeric conversion
cols = [
    "median_income",
    "population",
    "poverty_rate",
    "unemployment_rate"
]

df_2022[cols] = df_2022[cols].apply(
    pd.to_numeric,
    errors="coerce"
)

df_2022.head()

200
[["NAME","B19013_001E","B01003_001E","state","county"],
["Autauga County, Alabama","68315","58761","01","001"],
["Baldwin County, Alabama","71039","233420","01","003"],
["Barbour County, Alabama","39712","24877","01","005"],
["Bibb County, Alabama","50669","22251","01","007"],
["Blount County, Alaba
200
[["NAME","S1701_C03_001E","S2301_C04_001E","state","county"],
["Autauga County, Alabama","11.4","2.8","01","001"],
["Baldwin County, Alabama","10.2","3.4","01","003"],
["Barbour County, Alabama","24.2","5.8","01","005"],
["Bibb County, Alabama","20.6","8.7","01","007"],
["Blount County, Alabama","14

,county_name,median_income,population,state,county,poverty_rate,unemployment_rate
0,"Autauga County, Alabama",68315,58761,01,001,11.4,2.8
1,"Baldwin County, Alabama",71039,233420,01,003,10.2,3.4
2,"Barbour County, Alabama",39712,24877,01,005,24.2,5.8
3,"Bibb County, Alabama",50669,22251,01,007,20.6,8.7
4,"Blount County, Alabama",57440,59077,01,009,14.2,6.0

In [30]:
df_2022["fips"] = df_2022["state"] + df_2022["county"]
df_2021.head()

,county_name,median_income,population,state,county,poverty_rate,unemployment_rate,fips
0,"Autauga County, Alabama",62660,58239,01,001,13.6,2.8,01001
1,"Baldwin County, Alabama",64346,227131,01,003,9.2,3.7,01003
2,"Barbour County, Alabama",36422,25259,01,005,26.5,8.6,01005
3,"Bibb County, Alabama",54277,22412,01,007,16.9,9.7,01007
4,"Blount County, Alabama",52830,58884,01,009,13.2,6.0,01009

In [31]:
df_2022.to_csv(
    "../data/raw/census_acs_2022.csv",
    index=False
)

In [32]:
#year 2023
API_KEY = api_key

url_base = (
    "https://api.census.gov/data/2023/acs/acs5"
    "?get=NAME,B19013_001E,B01003_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

r1 = requests.get(url_base)

print(r1.status_code)
print(r1.text[:300])  

base = r1.json()

df_base = pd.DataFrame(base[1:], columns=base[0])

url_subject = (
    "https://api.census.gov/data/2023/acs/acs5/subject"
    "?get=NAME,S1701_C03_001E,S2301_C04_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

r2 = requests.get(url_subject)

print(r2.status_code)
print(r2.text[:300])

subject = r2.json()

df_subject = pd.DataFrame(subject[1:], columns=subject[0])


# Rename

df_base.rename(columns={
    "NAME": "county_name",
    "B19013_001E": "median_income",
    "B01003_001E": "population"
}, inplace=True)

df_subject.rename(columns={
    "S1701_C03_001E": "poverty_rate",
    "S2301_C04_001E": "unemployment_rate"
}, inplace=True)


# Merge

df_2023 = df_base.merge(
    df_subject[
        ["state","county","poverty_rate","unemployment_rate"]
    ],
    on=["state","county"],
    how="left"
)

# numeric conversion
cols = [
    "median_income",
    "population",
    "poverty_rate",
    "unemployment_rate"
]

df_2023[cols] = df_2023[cols].apply(
    pd.to_numeric,
    errors="coerce"
)

df_2023.head()

200
[["NAME","B19013_001E","B01003_001E","state","county"],
["Autauga County, Alabama","69841","59285","01","001"],
["Baldwin County, Alabama","75019","239945","01","003"],
["Barbour County, Alabama","44290","24757","01","005"],
["Bibb County, Alabama","51215","22152","01","007"],
["Blount County, Alaba
200
[["NAME","S1701_C03_001E","S2301_C04_001E","state","county"],
["Autauga County, Alabama","10.7","2.5","01","001"],
["Baldwin County, Alabama","10.5","3.2","01","003"],
["Barbour County, Alabama","21.9","5.7","01","005"],
["Bibb County, Alabama","20.5","10.0","01","007"],
["Blount County, Alabama","1

,county_name,median_income,population,state,county,poverty_rate,unemployment_rate
0,"Autauga County, Alabama",69841,59285,01,001,10.7,2.5
1,"Baldwin County, Alabama",75019,239945,01,003,10.5,3.2
2,"Barbour County, Alabama",44290,24757,01,005,21.9,5.7
3,"Bibb County, Alabama",51215,22152,01,007,20.5,10.0
4,"Blount County, Alabama",61096,59292,01,009,14.1,5.8

In [33]:
df_2023["fips"] = df_2023["state"] + df_2023["county"]
df_2023.head()

,county_name,median_income,population,state,county,poverty_rate,unemployment_rate,fips
0,"Autauga County, Alabama",69841,59285,01,001,10.7,2.5,01001
1,"Baldwin County, Alabama",75019,239945,01,003,10.5,3.2,01003
2,"Barbour County, Alabama",44290,24757,01,005,21.9,5.7,01005
3,"Bibb County, Alabama",51215,22152,01,007,20.5,10.0,01007
4,"Blount County, Alabama",61096,59292,01,009,14.1,5.8,01009

In [34]:
df_2023.to_csv(
    "../data/raw/census_acs_2023.csv",
    index=False
)

In [37]:
API_KEY = api_key

url_base = (
    "https://api.census.gov/data/2024/acs/acs5"
    "?get=NAME,B19013_001E,B01003_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

r1 = requests.get(url_base)

print(r1.status_code)
print(r1.text[:300])  

base = r1.json()

df_base = pd.DataFrame(base[1:], columns=base[0])

url_subject = (
    "https://api.census.gov/data/2024/acs/acs5/subject"
    "?get=NAME,S1701_C03_001E,S2301_C04_001E"
    "&for=county:*"
    f"&key={API_KEY}"
)

r2 = requests.get(url_subject)

print(r2.status_code)
print(r2.text[:300])

subject = r2.json()

df_subject = pd.DataFrame(subject[1:], columns=subject[0])


# Rename

df_base.rename(columns={
    "NAME": "county_name",
    "B19013_001E": "median_income",
    "B01003_001E": "population"
}, inplace=True)

df_subject.rename(columns={
    "S1701_C03_001E": "poverty_rate",
    "S2301_C04_001E": "unemployment_rate"
}, inplace=True)


# Merge

df_2024 = df_base.merge(
    df_subject[
        ["state","county","poverty_rate","unemployment_rate"]
    ],
    on=["state","county"],
    how="left"
)

# numeric conversion
cols = [
    "median_income",
    "population",
    "poverty_rate",
    "unemployment_rate"
]

df_2024[cols] = df_2024[cols].apply(
    pd.to_numeric,
    errors="coerce"
)

df_2024.head()

200
[["NAME","B19013_001E","B01003_001E","state","county"],
["Autauga County, Alabama","72481","59947","01","001"],
["Baldwin County, Alabama","78775","246989","01","003"],
["Barbour County, Alabama","46042","24643","01","005"],
["Bibb County, Alabama","52541","22130","01","007"],
["Blount County, Alaba
200
[["NAME","S1701_C03_001E","S2301_C04_001E","state","county"],
["Autauga County, Alabama","11.3","2.4","01","001"],
["Baldwin County, Alabama","10.1","3.0","01","003"],
["Barbour County, Alabama","21.4","7.8","01","005"],
["Bibb County, Alabama","22.5","12.1","01","007"],
["Blount County, Alabama","1

,county_name,median_income,population,state,county,poverty_rate,unemployment_rate
0,"Autauga County, Alabama",72481,59947,01,001,11.3,2.4
1,"Baldwin County, Alabama",78775,246989,01,003,10.1,3.0
2,"Barbour County, Alabama",46042,24643,01,005,21.4,7.8
3,"Bibb County, Alabama",52541,22130,01,007,22.5,12.1
4,"Blount County, Alabama",64190,59518,01,009,12.9,5.0

In [38]:
df_2024["fips"] = df_2024["state"] + df_2024["county"]
df_2024.head()

,county_name,median_income,population,state,county,poverty_rate,unemployment_rate,fips
0,"Autauga County, Alabama",72481,59947,01,001,11.3,2.4,01001
1,"Baldwin County, Alabama",78775,246989,01,003,10.1,3.0,01003
2,"Barbour County, Alabama",46042,24643,01,005,21.4,7.8,01005
3,"Bibb County, Alabama",52541,22130,01,007,22.5,12.1,01007
4,"Blount County, Alabama",64190,59518,01,009,12.9,5.0,01009

In [39]:
df_2024.to_csv(
    "../data/raw/census_acs_2024.csv",
    index=False
)