In [1]:
import pandas as pd
import numpy as np

**CDC Overdose Data**
- Pick only the columns that I will want
- Is there a county FIPS field?

In [2]:
cdc = pd.read_csv("../data/raw/2024 Cause of Death.csv")
cdc

,Notes,County,County Code,Sex,Sex Code,Year,Year Code,Cause of death,Cause of death Code,Place of Death,Place of Death Code,Deaths,Population,Crude Rate,Crude Rate Lower 95% Confidence Interval,Crude Rate Upper 95% Confidence Interval
0,NaN,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Decedent's home,4.0,15.0,Not Applicable,Not Applicable,Not Applicable,Not Applicable
1,NaN,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Other,7.0,12.0,Not Applicable,Not Applicable,Not Applicable,Not Applicable
2,NaN,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Decedent's home,4.0,23.0,Not Applicable,Not Applicable,Not Applicable,Not Applicable
3,NaN,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Other,7.0,12.0,Not Applicable,Not Applicable,Not Applicable,Not Applicable
4,NaN,"Jefferson County, AL",1073.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Medical Facility - Outpatient or ER,2.0,10.0,Not Applicable,Not Applicable,Not Applicable,Not Applicable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1536,"a result, users should consider that the actua...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1537,"deaths, with a crude rate of approximately 41....",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1538,"100,000 population. These deaths will not be u...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1539,10. Changes to cause of death classification a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1540,http://wonder.cdc.gov/wonder/help/ucd-expanded...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
cdc = cdc.drop(columns=['Population', 
                        'Crude Rate', 
                        'Crude Rate Lower 95% Confidence Interval', 
                        'Crude Rate Upper 95% Confidence Interval',
                        'Notes'])
cdc.head(5)

,County,County Code,Sex,Sex Code,Year,Year Code,Cause of death,Cause of death Code,Place of Death,Place of Death Code,Deaths
0,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Decedent's home,4.0,15.0
1,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Other,7.0,12.0
2,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Decedent's home,4.0,23.0
3,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Other,7.0,12.0
4,"Jefferson County, AL",1073.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Medical Facility - Outpatient or ER,2.0,10.0

In [4]:
cdc = cdc.rename(columns={
    "County": "county",
    "County Code": "fips",
    "Year": "year",
    "Deaths": "deaths"
})

cdc["fips"] = cdc["fips"].astype(str).str.zfill(5)

In [5]:
cdc["deaths"].unique()
cdc["deaths"] = pd.to_numeric(
    cdc["deaths"],
    errors="coerce"
)

In [6]:
cdc = cdc.dropna(subset=["deaths"])
cdc

,county,fips,Sex,Sex Code,year,Year Code,Cause of death,Cause of death Code,Place of Death,Place of Death Code,deaths
0,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Decedent's home,4.0,15.0
1,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Other,7.0,12.0
2,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Decedent's home,4.0,23.0
3,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Other,7.0,12.0
4,"Jefferson County, AL",1073.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Medical Facility - Outpatient or ER,2.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...
1475,"Milwaukee County, WI",55079.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Other,7.0,44.0
1476,"Milwaukee County, WI",55079.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Decedent's home,4.0,73.0
1477,"Milwaukee County, WI",55079.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Other,7.0,43.0
1478,"Racine County, WI",55101.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Decedent's home,4.0,11.0
1479,"Waukesha County, WI",55133.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Decedent's home,4.0,10.0

In [14]:
cdc.to_csv(
    "../data/cleaned/cdc_cleaned_2024.csv",
    index=False
)

**Census Data**
- What variables did you pull?
- Do you have:
  - state
  - county
  - FIPS
  - income
  - poverty
  - unemployment

In [7]:
census = pd.read_csv('../data/raw/census_acs_2024.csv')
census.head(2)

               county_name  median_income  population  state  county  fips
0  Autauga County, Alabama          72481       59947      1       1  1001
1  Baldwin County, Alabama          78775      246989      1       3  1003

In [8]:
census[['county', 'state']] = census['county_name'].str.split(',', expand=True)
census = census.drop(columns = ['county_name'])

census["fips"] = census["fips"].astype(str).str.zfill(5)

cols_to_back = ['median_income', 'population']

census = census[[col for col in census.columns if col not in cols_to_back] + cols_to_back]
census.head(5)

      state          county   fips  median_income  population
0   Alabama  Autauga County  01001          72481       59947
1   Alabama  Baldwin County  01003          78775      246989
2   Alabama  Barbour County  01005          46042       24643
3   Alabama     Bibb County  01007          52541       22130
4   Alabama   Blount County  01009          64190       59518

In [9]:
census["median_income"] = pd.to_numeric(
    census["median_income"],
    errors="coerce"
)

census["population"] = pd.to_numeric(
    census["population"],
    errors="coerce"
)

In [10]:
census.isna().sum()

state            0
county           0
fips             0
median_income    0
population       0
dtype: int64

So here I only have median income and population for each county in the US. I want to get unemployment and poverty rates for each county. I will calculate that after merging.

In [13]:
census.to_csv(
    "../data/cleaned/census_clean_2024.csv",
    index=False
)

**SAMHSA Data**
Do I have:
 - facility name
 - state
 - county
 - ZIP
 - services offered

My main goal is to get a count of of the facilities per county that provide treatments for opioids.

In [29]:
samhsa = pd.read_csv('../data/raw/NSUMHSS_2024_PUF_CSV.csv')
samhsa.head(2)

,MPRID,INSU,INMH,LOCATIONSTATE,FOCUS,SUTRTMNTALSO,JAIL,OTHNONTX,DETOX,TREATMT_SU,...,VAMAINTAIN,VAFUAPPTMSSD,VASPC_MH,VACAREMGR_MH,VAPROGSUPP_MH,VAHIGHRISKHI_MH,VAHIGHRISKRC_MH,VAHIGHRISKOP_MH,TSU_SU,TSU_MH
0,100002G,1,1,IN,3,L,0,1,0,1,...,L,L,L,L,L,L,L,L,1,1
1,100101S,1,1,TN,3,L,0,1,0,1,...,L,L,L,L,L,L,L,L,1,1

In [30]:
[c for c in samhsa.columns if "COUNTY" in c.upper()]

[]

In [31]:
[c for c in samhsa.columns if "ZIP" in c.upper()]

['ZIPRA_NO', 'ZIPRA_ORAL', 'ZIPRA_INJ', 'ZIPRA_DK']

In [32]:
[c for c in samhsa.columns if "METH" in c.upper()]

[]

In [33]:
[c for c in samhsa.columns if "BUP" in c.upper()]

['OTXBUP', 'HIBUPNUM', 'RCBUPNUM', 'OPBUPNUM']

In [34]:
[c for c in samhsa.columns if "OP" in c.upper()]

['DETXOP',
 'CTYPEOP',
 'NOPRETXSRVC',
 'NOPHARMSRVC',
 'OPIOIDMAINT',
 'OPIOIDWDRAW',
 'OPIOIDDETOX',
 'OPIOIDDLOFE',
 'OPIOIDNAL',
 'OPIOIDOTH',
 'NOOPIOIDMEDSRVC',
 'SACOUNOPIOID',
 '_12STEPOPIOID',
 'BRIEFOPIOID',
 'COGBTOPIOID',
 'CONMGMTOPIOID',
 'MOTIVATEOPIOID',
 'TRAUMACOPIOID',
 'ANGERMOPIOID',
 'MATRIXMOPIOID',
 'CRVOUCHEROPIOID',
 'RELPREVOPIOID',
 'TELEMEDOPIOID',
 'APPRCHOTHOPIOID',
 'NOAPPRCHOPIOID',
 'SETTINGOP',
 'DROPE_NO',
 'DROPE_INJ',
 'DROPE_DK',
 'HALOP_NO',
 'HALOP_ORAL',
 'HALOP_INJ',
 'HALOP_DK',
 'PIMOZ_TOP',
 'FSTGEN1OTH_TOP',
 'FSTGEN2OTH_TOP',
 'FSTGEN3OTH_TOP',
 'ASENA_TOP',
 'ILOPE_NO',
 'ILOPE_ORAL',
 'ILOPE_DK',
 'SECGEN1OTH_TOP',
 'SECGEN2OTH_TOP',
 'SECGEN3OTH_TOP',
 'ADOPTSECLUSION',
 'NOPUBADDR',
 'T_CLIOP_O',
 'T_CLIOP',
 'OPMETNUM',
 'OPBUPNUM',
 'OPVIVNUM',
 'OPDISNUM',
 'OPNALNUM',
 'OPACAMNUM',
 'OPSERV',
 'OPTOTAL_O',
 'OPTOTAL',
 'OPSEXTOTM_O',
 'OPSEXTOTM',
 'OPSEXPERM',
 'OPSEXTOTF_O',
 'OPSEXTOTF',
 'OPSEXPERF',
 'OPAGETOT017_O',
 'OPAGETOT017',
 'OPAGEPER017',
 'OPAGETOT1864_O',
 'OPAGETOT1864',
 'OPAGEPER1864',
 'OPAGETOT65_O',
 'OPAGETOT65',
 'OPAGEPER65',
 'OPETHTOTHISP_O',
 'OPETHTOTHISP',
 'OPETHPERHISP',
 'OPETHTOTNONHISP_O',
 'OPETHTOTNONHISP',
 'OPETHPERNONHISP',
 'OPETHTOTUNK_O',
 'OPETHTOTUNK',
 'OPETHPERUNK',
 'OPRACETOTINDIAN_O',
 'OPRACETOTINDIAN',
 'OPRACEPERINDIAN',
 'OPRACETOTASIAN_O',
 'OPRACETOTASIAN',
 'OPRACEPERASIAN',
 'OPRACETOTBLK_O',
 'OPRACETOTBLK',
 'OPRACEPERBLK',
 'OPRACETOTHAWPAC_O',
 'OPRACETOTHAWPAC',
 'OPRACEPERHAWPAC',
 'OPRACETOTWHIT_O',
 'OPRACETOTWHIT',
 'OPRACEPERWHIT',
 'OPRACETOTMR_O',
 'OPRACETOTMR',
 'OPRACEPERMR',
 'OPRACETOTUNK_O',
 'OPRACETOTUNK',
 'OPRACEPERUNK',
 'OPLEGALTOTVOL_O',
 'OPLEGALTOTVOL',
 'OPLEGALPERVOL',
 'OPLEGALTOTNONFOREN_O',
 'OPLEGALTOTNONFOREN',
 'OPLEGALPERNONFOREN',
 'OPLEGALTOTFOREN_O',
 'OPLEGALTOTFOREN',
 'OPLEGALPERFOREN',
 'VAHIGHRISKOP_SU',
 'VAHIGHRISKOP_MH']