In [1]:
import pandas as pd
import numpy as np

**CDC Overdose Data**
- Pick only the columns that I will want
- Is there a county FIPS field?

In [2]:
cdc = pd.read_csv("../data/raw/2024 Cause of Death.csv")
cdc

,Notes,County,County Code,Sex,Sex Code,Year,Year Code,Cause of death,Cause of death Code,Place of Death,Place of Death Code,Deaths,Population,Crude Rate,Crude Rate Lower 95% Confidence Interval,Crude Rate Upper 95% Confidence Interval
0,NaN,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Decedent's home,4.0,15.0,Not Applicable,Not Applicable,Not Applicable,Not Applicable
1,NaN,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Other,7.0,12.0,Not Applicable,Not Applicable,Not Applicable,Not Applicable
2,NaN,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Decedent's home,4.0,23.0,Not Applicable,Not Applicable,Not Applicable,Not Applicable
3,NaN,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Other,7.0,12.0,Not Applicable,Not Applicable,Not Applicable,Not Applicable
4,NaN,"Jefferson County, AL",1073.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Medical Facility - Outpatient or ER,2.0,10.0,Not Applicable,Not Applicable,Not Applicable,Not Applicable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1536,"a result, users should consider that the actua...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1537,"deaths, with a crude rate of approximately 41....",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1538,"100,000 population. These deaths will not be u...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1539,10. Changes to cause of death classification a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1540,http://wonder.cdc.gov/wonder/help/ucd-expanded...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
cdc = cdc.drop(columns=['Population', 
                        'Crude Rate', 
                        'Crude Rate Lower 95% Confidence Interval', 
                        'Crude Rate Upper 95% Confidence Interval',
                        'Notes'])
cdc.head(5)

,County,County Code,Sex,Sex Code,Year,Year Code,Cause of death,Cause of death Code,Place of Death,Place of Death Code,Deaths
0,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Decedent's home,4.0,15.0
1,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Other,7.0,12.0
2,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Decedent's home,4.0,23.0
3,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Other,7.0,12.0
4,"Jefferson County, AL",1073.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Medical Facility - Outpatient or ER,2.0,10.0

In [4]:
cdc = cdc.rename(columns={
    "County": "county",
    "County Code": "fips",
    "Year": "year",
    "Deaths": "deaths"
})

cdc["fips"] = cdc["fips"].astype(str).str.zfill(5)

In [5]:
cdc["deaths"].unique()
cdc["deaths"] = pd.to_numeric(
    cdc["deaths"],
    errors="coerce"
)

In [6]:
cdc = cdc.dropna(subset=["deaths"])
cdc

,county,fips,Sex,Sex Code,year,Year Code,Cause of death,Cause of death Code,Place of Death,Place of Death Code,deaths
0,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Decedent's home,4.0,15.0
1,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Other,7.0,12.0
2,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Decedent's home,4.0,23.0
3,"Jefferson County, AL",1073.0,Female,F,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Other,7.0,12.0
4,"Jefferson County, AL",1073.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Medical Facility - Outpatient or ER,2.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...
1475,"Milwaukee County, WI",55079.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Other,7.0,44.0
1476,"Milwaukee County, WI",55079.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Decedent's home,4.0,73.0
1477,"Milwaukee County, WI",55079.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Other,7.0,43.0
1478,"Racine County, WI",55101.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to other ...,X44,Decedent's home,4.0,11.0
1479,"Waukesha County, WI",55133.0,Male,M,2024.0,2024.0,Accidental poisoning by and exposure to narcot...,X42,Decedent's home,4.0,10.0

In [7]:
cdc.to_csv(
    "../data/cleaned/cdc_cleaned_2024.csv",
    index=False
)

**Census Data**
- What variables did you pull?
- Do you have:
  - state
  - county
  - FIPS
  - income
  - poverty
  - unemployment

In [8]:
census = pd.read_csv('../data/raw/census_acs_2024.csv')
census.head(2)

               county_name  median_income  population  state  county  fips
0  Autauga County, Alabama          72481       59947      1       1  1001
1  Baldwin County, Alabama          78775      246989      1       3  1003

In [9]:
census[['county', 'state']] = census['county_name'].str.split(',', expand=True)
census = census.drop(columns = ['county_name'])

census["fips"] = census["fips"].astype(str).str.zfill(5)

cols_to_back = ['median_income', 'population']

census = census[[col for col in census.columns if col not in cols_to_back] + cols_to_back]
census.head(5)

      state          county   fips  median_income  population
0   Alabama  Autauga County  01001          72481       59947
1   Alabama  Baldwin County  01003          78775      246989
2   Alabama  Barbour County  01005          46042       24643
3   Alabama     Bibb County  01007          52541       22130
4   Alabama   Blount County  01009          64190       59518

In [10]:
census["median_income"] = pd.to_numeric(
    census["median_income"],
    errors="coerce"
)

census["population"] = pd.to_numeric(
    census["population"],
    errors="coerce"
)

In [11]:
census.isna().sum()

state            0
county           0
fips             0
median_income    0
population       0
dtype: int64

So here I only have median income and population for each county in the US. I want to get unemployment and poverty rates for each county. I will calculate that after merging.

In [12]:
census.to_csv(
    "../data/cleaned/census_clean_2024.csv",
    index=False
)

**SAMHSA Data**
Do I have:
 - facility name
 - state
 - county
 - ZIP
 - services offered

My main goal is to get a count of of the facilities per county that provide treatments for opioids.

In [13]:
facilities = pd.read_csv('../data/raw/2025_MH_Facilities_for_All_City_All.csv')
facilities.head(2)

,name1,name2,street1,street2,city,state,zip,phone,intake1,intake2,intake1a,intake2a,service_code_info
0,SpectraCare Health Systems,Henry County Clinic,219 Dothan Road,NaN,Abbeville,AL,36310.0,800-951-4357,NaN,NaN,NaN,NaN,SA MH SUMH * OP * CMHC * CHLOR FLUPH HALOP ARI...
1,SpectraCare Health Systems,Henry County Day Treatment,1242 U.S. Highway 431 South,NaN,Abbeville,AL,36310.0,800-951-4357,334-951-4357,NaN,NaN,NaN,MH SUMH * OP * CMHC * CHLOR FLUPH HALOP ARIPI ...

In [14]:
facilities["service_code_info"].head(10)

0    SA MH SUMH * OP * CMHC * CHLOR FLUPH HALOP ARI...
1    MH SUMH * OP * CMHC * CHLOR FLUPH HALOP ARIPI ...
2    SA MH SUMH * OP * OMH * CHLOR HALOP ARIPI CARI...
3    SA MH SUMH * OP PHP * CMHC * CHLOR FLUPH HALOP...
4    SA MH SUMH * PHP RES * MSMH * CHLOR FLUPH HALO...
5    SA MH SUMH * OP PHP * CMHC * HALOP RISPE ANTPY...
6    SA MH SUMH * HI * IPSY * CHLOR FLUPH HALOP LOX...
7    SA MH SUMH * RES * RTCA * LOXAP ARIPI OLANZ/FL...
8    MH SUMH * RES * RTCA * CHLOR FLUPH HALOP ARIPI...
9    MH SUMH * OP * CMHC * HALOP ARIPI OLANZ QUETI ...
Name: service_code_info, dtype: object

In [15]:
facilities["substance_abuse"] = facilities["service_code_info"].str.contains(
    r"\bSA\b",
    na=False
)

facilities["substance_abuse"].value_counts()

substance_abuse
True     10740
False     3538
Name: count, dtype: int64

In [16]:
facilities["methadone"] = facilities["service_code_info"].str.contains(
    "BUP",
    case=False,
    na=False
)

facilities["methadone"].value_counts()

methadone
False    14278
Name: count, dtype: int64

In [17]:
facilities["buprenorphine"] = facilities["service_code_info"].str.contains(
    "BUP",
    case=False,
    na=False
)

facilities["buprenorphine"].value_counts()

buprenorphine
False    14278
Name: count, dtype: int64

In [18]:
facilities["substance_abuse"] = facilities["service_code_info"].str.contains(
    r"\bSA\b",
    na=False
)

In [19]:
sa_facilities = facilities[facilities["substance_abuse"]]

In [20]:
sa_facilities

,name1,name2,street1,street2,city,state,zip,phone,intake1,intake2,intake1a,intake2a,service_code_info,substance_abuse,methadone,buprenorphine
0,SpectraCare Health Systems,Henry County Clinic,219 Dothan Road,NaN,Abbeville,AL,36310.0,800-951-4357,NaN,NaN,NaN,NaN,SA MH SUMH * OP * CMHC * CHLOR FLUPH HALOP ARI...,True,False,False
2,Integrea Community Mental Health Syste,Nan Coley Murphy Center TCC,1870 Highway 22 West,NaN,Alexander City,AL,35010.0,334-742-2700,334-742-2877,NaN,NaN,NaN,SA MH SUMH * OP * OMH * CHLOR HALOP ARIPI CARI...,True,False,False
3,South Central Alabama MHC,Covington County Mental Health Center,19815 Bay Branch Road,NaN,Andalusia,AL,36420.0,334-222-2523,877-530-0002,NaN,NaN,NaN,SA MH SUMH * OP PHP * CMHC * CHLOR FLUPH HALOP...,True,False,False
4,South Central Alabama MHC,Montezuma Complex,205 Academy Drive,NaN,Andalusia,AL,36420.0,334-428-5050,877-530-0002,NaN,NaN,NaN,SA MH SUMH * PHP RES * MSMH * CHLOR FLUPH HALO...,True,False,False
5,Highland Health Systems,New Directions,331 East 8th Street,NaN,Anniston,AL,36207.0,256-236-3403,NaN,NaN,NaN,NaN,SA MH SUMH * OP PHP * CMHC * HALOP RISPE ANTPY...,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14098,High Country Behavioral Health,Thayne,250 Van Noy Parkway,NaN,Thayne,WY,83127.0,307-885-9883,NaN,NaN,NaN,NaN,SA MH SUMH * OP * CMHC * CHLOR FLUPH HALOP LOX...,True,False,False
14099,High Country Behavioral Health,Thermopolis Office,121 South 4th Street,NaN,Thermopolis,WY,82443.0,307-864-3138,NaN,307-864-2247,NaN,NaN,SA MH SUMH * OP * CMHC * CHLOR FLUPH HALOP LOX...,True,False,False
14100,Volunteers of America Northern Rockies,Torrington Clinic,501 Albany Avenue,NaN,Torrington,WY,82240.0,307-532-4091,NaN,NaN,NaN,NaN,SA MH SUMH * OP * CMHC * AT CBT CFT DBT GT IDD...,True,False,False
14101,Volunteers of America Northern Rockies,Wheatland Clinic,1954 West Mariposa Parkway,NaN,Wheatland,WY,82201.0,307-322-3190,NaN,NaN,NaN,NaN,SA MH SUMH * OP * CMHC * AT CBT CFT DBT GT IDD...,True,False,False
14102,Cloud Peak Counseling Center,DBA Oxbow Center,401 South 23rd Street,NaN,Worland,WY,82401.0,307-347-6165,NaN,NaN,NaN,NaN,SA MH SUMH * OP * CMHC * ANTPYCH * AT CBT CFT ...,True,False,False

In [21]:
facilities["substance_abuse"] = facilities["service_code_info"].str.contains(
    r"\bSA\b",
    na=False
)

facilities["substance_abuse"].value_counts()

substance_abuse
True     10740
False     3538
Name: count, dtype: int64

Let's keep only the Substance abuse facilities.

In [24]:
facilities["substance_abuse"] = (
    facilities["service_code_info"]
    .str.contains(r"\bSA\b", na=False)
)

sa = facilities[
    facilities["substance_abuse"]
].copy()

print(sa.shape)

(10740, 16)

In [25]:
sa["zip"] = (
    sa["zip"]
    .astype(str)
    .str.extract(r"(\d{5})")[0]
)

sa = sa.dropna(subset=["zip"])

sa["zip"] = (
    sa["zip"]
    .astype(str)
    .str.zfill(5)
)

sa[["state","zip"]].head()

  state    zip
0    AL  36310
2    AL  35010
3    AL  36420
4    AL  36420
5    AL  36207

Now we need to get a count of the facility per county based on Zip Code.

In [30]:
facility_saf_counts = (
    sa
    .groupby(
        ["state", "zip"]
    )
    .size()
    .reset_index(
        name="facility_count"
    )
)

facility_saf_counts.head()

  state    zip  facility_count
0    AK  99501               2
1    AK  99503               6
2    AK  99507               1
3    AK  99508              10
4    AK  99518               2

In [29]:
facility_saf_counts.to_csv(
    "../data/cleaned/samhsa_facilities_zip.csv",
    index=False
)